### ISSUE TITLE
Maybe move to Qt.py as a Qt Shim

### ISSUE THREAD

**Issue by nebukadhezer** [hannesdelbeke/unimenu#46]
Hey @hannesdelbeke 

I really like all your repos, I was wondering if you would consider a PR moving unimenu to Qt.py ?
https://github.com/mottosso/Qt.py

And in Appdetect instead of importing running for 
sys.executable would be faster... I could also prep a PR for that..
But wanted to know if these would be welcome changes or not ?

Let me know what you think

**Comment by hannesdelbeke** [comment]
Hi, I'm familiar with qt.py, used it a lot myself in the past.
What problem would it solve if we used qt.py instead of the current qt implementation?

I'm not following exactly what you mean with the app detect and sys.executable. can you  rxplain a bit more or perhaps dhow that PR. Always interested in seeing a better way. 
Note that sys.exec does not always behave as expected in all apps. E.g. in old blender versions it did not return the blender python interpreter path AFAIK

**Comment by hannesdelbeke** [comment]
And for app detect if optimization is needed we can also always swap to importlib instead of attempt an import. Checking the package name. Its a lot faster but a bit more code

**Comment by hannesdelbeke** [comment]
Can you let me know which code you rsted in maya? Adding MAYA will use the old maya unimenu, instead of the new and better qt maya menu setup. Both work but new one has more features i believe. The test code migt need updating

**Comment by hannesdelbeke** [comment]
Can you make a pr for the sys exec. But just for 1 app? To see how you have it in mind. Maybe maya or blender?

**Comment by nebukadhezer** [comment]
```python
import unimenu
menu = unimenu.Node(label="my menu")  # create a menu
item = unimenu.Node(label="hi", command='print("hi")')  # create a menu item
menu.items.append(item)  # add the item to the menu
menu.setup()  # setup the menu in the app, parented by default to the main menu bar
```

produces this in Maya 2022.


# Error: 'NoneType' object has no attribute 'findChild'
# Traceback (most recent call last):
#   File "<maya console>", line 5, in <module>
#   File "c:\users\johannes\packages\unimenu\0.4.1\88a70aca30cb79a278872594adf043dc6c40af99\python\unimenu\apps\_abstract.py", line 205, in setup
#     parent_app_node = parent_app_node or self._default_root_parent
#   File "c:\users\johannes\packages\unimenu\0.4.1\88a70aca30cb79a278872594adf043dc6c40af99\python\unimenu\apps\qt.py", line 48, in _default_root_parent
#     menu_bar = main_window.findChild(QtWidgets.QMenuBar)
# AttributeError: 'NoneType' object has no attribute 'findChild' #

**Comment by nebukadhezer** [comment]
https://github.com/hannesdelbeke/detect-app/pull/3

Here is the sample pr how I would implement the app detection for dccs where it is possible
