### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AlexSegal** [hannesdelbeke/unimenu#51]
### Discussed in https://github.com/hannesdelbeke/unimenu/discussions/49

<div type='discussions-op-text'>

<sup>Originally posted by **AlexSegal** July 17, 2023</sup>
Hello @hannesdelbeke! 

I tried unimenu and I really love the neat way you came up with to create menus in different DCCs! Thank you so much! One question though: you did not specify the license (unless I missed it). As far as I understand that prevents me from using the code in the studio environment, since it's not open source by default. It would be great if you could add the license to the project (or point me to one if it exists).

Thanks again!</div>

**Comment by hannesdelbeke** [comment]
done
